name: Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 配置 JDK 版本
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      # 配置 Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 构建 Gradle 项目
      - name: Build with Gradle
        run: ./gradlew.bat clean packageDistributionForCurrentOS --info --stacktrace

      # 展示错误日志
      - name: Show error log
        if: failure()
        run: |
          echo "=== Error Log List ==="
          ls -l D:\a\pomodoro_timer\pomodoro_timer\build\compose\logs\packageExe\
          
          echo "=== Most Recent Error Log ==="
          cat build/compose/logs/packageExe/jpackage-$(ls -t build/compose/logs/packageExe/jpackage-*-err.txt | head -n1)
          
          echo "=== Most Recent Output Log ==="
          cat build/compose/logs/packageExe/jpackage-$(ls -t build/compose/logs/packageExe/jpackage-*-out.txt | head -n1)

      # 创建 Release 并上传构建产物
      - name: Upload build artifacts for release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/compose/binaries/exe/*.exe, build/compose/binaries/msi/*.msi"
          tag: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          bodyFile: "CHANGELOG.md"
